server:
 port: 9001
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/redisson?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
   username: root
   password: root
 redis:
   host: 47.107.53.172
   port: 6379
   password: redispassword
   database: 0
   timeout: 2000ms
   redisson:
     config: "classpath:redisson-single.yml"