server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/like?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    password: redispassword
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    cluster:
      nodes:
        - 47.107.53.172:6391
        - 47.107.53.172:6392
        - 47.107.53.172:6393
        - 47.107.53.172:6394
        - 47.107.53.172:6395
        - 47.107.53.172:6396

